interface ITask {
  id:number
  phase_id: number
  name: string
  description: string
  responsible_id: number
  is_complete: boolean
  star_date_planned: string
  end_date_planned: string
  start_date_actual: string
  end_date_actual: string
  priority: string
}

interface IPhase {
  id:number
  project_id: number
  name: string
  description: string
  weight: number
  responsible_id: number
  star_date_planned: string
  end_date_planned: string
  start_date_actual: string
  end_date_actual: string
  tasks: Array<ITask>
}

interface IProject {
  id: number
  code: string
  name: string
  description: string
  star_date_planned: string
  end_date_planned: string
  start_date_actual: string
  end_date_actual: string
  status_id: number
  phases: Array<IPhase>
}

export const projects: IProject[] = [
  {
    id: 1,
    code: 'prox-001',
    name: 'Projecto benchark',
    description: 'Administracion digital de datos de la direccion dap',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:1,
        project_id: 1,
        name: 'fase 1 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:1,
            phase_id: 1,
            name: 'Tarea 1',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:2,
            phase_id: 1,
            name: 'Tarea 2',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:2,
        project_id: 1,
        name: 'fase 2 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:3,
            phase_id: 2,
            name: 'Tarea 1',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:4,
            phase_id: 2,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 2,
    code: 'prox-002',
    name: "Projecto KPI's",
    description: "Administracion digital de kpi's DAP",
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:3,
        project_id: 2,
        name: 'fase 1 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:5,
            phase_id: 3,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:6,
            phase_id: 3,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:4,
        project_id: 2,
        name: 'fase 2 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:7,
            phase_id: 4,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:8,
            phase_id: 4,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 3,
    code: 'prox-003',
    name: 'Strategic Projecto',
    description: 'Administracion digital de proyectos DAP',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:5,
        project_id: 3,
        name: 'fase 1 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:9,
            phase_id: 5,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:10,
            phase_id: 5,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 4,
    code: 'prox-004',
    name: 'Engagement',
    description:'Administracion digital de metricas y alcance de redes sociales DAP, alcance de videos en tiktok muy pronto areometro',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:6,
        project_id: 4,
        name: 'fase 1 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:11,
            phase_id: 6,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:12,
            phase_id: 6,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:7,
        project_id: 4,
        name: 'fase 2 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:13,
            phase_id: 7,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:14,
            phase_id: 7,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 5,
    code: 'prox-005',
    name: 'Task Board',
    description: 'Administracion digital de tareas en la DAP',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:8,
        project_id: 5,
        name: 'fase 1 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.4,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:15,
            phase_id: 8,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:16,
            phase_id: 8,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:9,
        project_id: 5,
        name: 'fase 2 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.5,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:17,
            phase_id: 9,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:18,
            phase_id: 9,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 6,
    code: 'prox-006',
    name: 'Back end',
    description: 'Trabajar en laravel 12 el backend para los proyectos propuestos en la DAP',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:10,
        project_id: 6,
        name: 'fase 1 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:19,
            phase_id: 10,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:20,
            phase_id: 10,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:11,
        project_id: 6,
        name: 'fase 2 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:21,
            phase_id: 11,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:22,
            phase_id: 11,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:12,
        project_id: 6,
        name: 'fase 3 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:23,
            phase_id: 12,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:24,
            phase_id: 12,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:13,
        project_id: 6,
        name: 'fase 4 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:25,
            phase_id: 13,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:26,
            phase_id: 13,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 7,
    code: 'prox-007',
    name: 'Front end',
    description:
      'Trabajar en vue.js 3 y typescript el frontend para los proyectos proyectos en la DAP',
    star_date_planned: '2025-12-08',
    end_date_planned: '2025-12-08',
    start_date_actual: '2025-12-08',
    end_date_actual: '2025-12-08',
    status_id: 1,
    phases: [
      {
        id:14,
        project_id: 7,
        name: 'fase 1 Projecto nuevo',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:27,
            phase_id: 14,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:28,
            phase_id: 14,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:15,
        project_id: 7,
        name: 'fase 2 Projecto inventado',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:29,
            phase_id: 15,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:30,
            phase_id: 15,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
  {
    id: 8,
    code: 'prox-008',
    name: 'Prueba con fechas nuevo',
    description: 'Prueba con fechas',
    star_date_planned: '2025-12-05',
    end_date_planned: '2025-12-20',
    start_date_actual: '2025-12-05',
    end_date_actual: '2025-12-20',
    status_id: 1,
    phases: [
      {
        id:16,
        project_id: 8,
        name: 'fase 1 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:31,
            phase_id: 16,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:32,
            phase_id: 16,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:17,
        project_id: 8,
        name: 'fase 2 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:33,
            phase_id: 17,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:34,
            phase_id: 17,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
      {
        id:18,
        project_id: 8,
        name: 'fase 3 Projecto benchark',
        description: 'Administracion digital de datos de la direccion dap',
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: '2025-12-08',
        end_date_planned: '2025-12-08',
        start_date_actual: '2025-12-08',
        end_date_actual: '2025-12-08',
        tasks: [
          {
            id:35,
            phase_id: 18,
            name: 'Tarea 1 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
          {
            id:36,
            phase_id: 18,
            name: 'Tarea 2 Projecto nuevo',
            description: 'Administracion digital de datos de la direccion dap',
            responsible_id: 1,
            is_complete:false,
            star_date_planned: '2025-12-08',
            end_date_planned: '2025-12-08',
            start_date_actual: '2025-12-08',
            end_date_actual: '2025-12-08',
            priority:'normal'
          },
        ],
      },
    ],
  },
]
