interface IPhase {
  project_id: number
  name: string
  description: string
  weight: number
  responsible_id: number
  star_date_planned: string
  end_date_planned: string
  start_date_actual: string
  end_date_actual: string
}

interface IProject {
  code: string
  name: string
  description: string
  star_date_planned: string
  end_date_planned: string
  start_date_actual: string
  end_date_actual: string
  status_id: number
  phases: Array<IPhase>
}

export const projects: IProject[] = [
  {
    code: "prox-001",
    name: "Projecto benchark",
    description: "Administracion digital de datos de la direccion dap",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 1,
        name: "fase 1 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 1,
        name: "fase 2 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-002",
    name: "Projecto KPI's",
    description: "Administracion digital de kpi's DAP",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 2,
        name: "fase 1 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 2,
        name: "fase 2 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-003",
    name: "Strategic Projecto",
    description: "Administracion digital de proyectos DAP",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 3,
        name: "fase 1 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-004",
    name: "Engagement",
    description: "Administracion digital de metricas y alcance de redes sociales DAP, alcance de videos en tiktok muy pronto areometro",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 4,
        name: "fase 2 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 4,
        name: "fase 3 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-005",
    name: "Task Board",
    description: "Administracion digital de tareas en la DAP",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 5,
        name: "fase 4 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.4,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 5,
        name: "fase 5 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.5,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-006",
    name: "Back end",
    description: "Trabajar en laravel 12 el backend para los proyectos propuestos en la DAP",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 6,
        name: "fase 1 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 6,
        name: "fase 2 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 6,
        name: "fase 3 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 6,
        name: "fase 1 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-007",
    name: "Front end",
    description: "Trabajar en vue.js 3 y typescript el frontend para los proyectos proyectos en la DAP",
    star_date_planned: "2025-12-08",
    end_date_planned: "2025-12-08",
    start_date_actual: "2025-12-08",
    end_date_actual: "2025-12-08",
    status_id: 1,
    phases: [
      {
        project_id: 7,
        name: "fase 2 Projecto nuevo",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 7,
        name: "fase 1 Projecto inventado",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  },
  {
    code: "prox-008",
    name: "Prueba con fechas nuevo",
    description: "Prueba con fechas",
    star_date_planned: "2025-12-05",
    end_date_planned: "2025-12-20",
    start_date_actual: "2025-12-05",
    end_date_actual: "2025-12-20",
    status_id: 1,
    phases: [
      {
        project_id: 8,
        name: "fase 1 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.1,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 8,
        name: "fase 2 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.2,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
      {
        project_id: 8,
        name: "fase 3 Projecto benchark",
        description: "Administracion digital de datos de la direccion dap",
        weight: 0.3,
        responsible_id: 1,
        star_date_planned: "2025-12-08",
        end_date_planned: "2025-12-08",
        start_date_actual: "2025-12-08",
        end_date_actual: "2025-12-08",
      },
    ],
  }
]
